### ISSUE TITLE
Schematic Cleanup

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/WS2812_Breakout#12]
1) flags should be 0.05 size

2) one of your VCC symbols needs to be rotated so it goes "up"

3) Let's include a text object indicating the acceptable VCC range. Might also be worth doing one for the reverse voltage protection included.

4) Change connector names to JP1 and JP2, theres no need for them to be up at 10 and 11.

5) Change "D1" to "U1", cause technically it's an IC. sorry this is slightly confusing considering that it's an LED and the correct prefix for leds is D

6) add "WS2812B" as a value for U1 (currently D1)

**Comment by PatrickAlberts** [comment]
Pete I have everything done here, but I eagle won't let me chage JP10 and 11 to JP 1 and 2, because they "already" exist?  Is there any way to combat this?

**Comment by mgrusin** [comment]
I've had the same problem and found that a standoff or logo or some other nonobvious part had the "JP" prefix (stupid!) You can export the BOM to see what it is, and If you find the offending part a library change is appreciated!

**Comment by PatrickAlberts** [comment]
Thanks guys.  I'm back online working again now, so I will check this out.

-P

**Comment by PatrickAlberts** [comment]
This worked perfectly thanks a bunch.
